package ru.stayyhydratedd.wbot.ShiftSheet.enums;

public enum ConditionContext {
    LOGIN,
    STARTUP_FLOW,
    ROOT_IDENTITY,
    MAIN_MENU,
    ROOT_FOLDER_MENU,
    PWZ_MENU,
    CHANGE_CURRENT_PWZ_INTERACTIVE_MENU,
    CREATE_NEW_PWZ,
    USER_MENU,
    CHANGE_CURRENT_ROOT_FOLDER_FROM_ROOT_FOLDER_MENU,
    CHANGE_CURRENT_ROOT_FOLDER_FROM_ROOT_IDENTITY,
    EMPLOYEE_MENU,
    CHANGE_CURRENT_EMPLOYEE,
    CREATE_NEW_EMPLOYEE_INTERACTIVE,
    CURRENT_EMPLOYEE_DATA_MENU,
    CURRENT_ROOT_FOLDER_DATA_MENU,
    EDIT_CURRENT_ROOT_FOLDER_DATA_MENU,
    ASK_YES_OR_NO
}
