create table app_user(
    id int generated by default as identity primary key,
    username varchar(100) not null,
    password varchar not null
);

create table app_role(
    id int generated by default as identity primary key,
    role_name varchar(50) unique not null
);

create table user_role(
    user_id int references app_user(id),
    role_id int references app_role(id),
    primary key (user_id, role_id)
);

create table app_settings(
    id int generated by default as identity primary key,
    pay_rate double precision check (pay_rate > 0),
    pwzs_folder_id varchar
);

create table root_folder(
    id           int generated by default as identity primary key,
    google_id    varchar not null unique,
    title        varchar not null,
    created_time timestamp with time zone not null,
    app_settings int references app_settings (id)
);

create table employee(
    id int generated by default as identity primary key,
    name varchar(100) not null,
    pay_rate double precision,
    gmail varchar(255) unique,
    phone_number varchar(12) unique
);

create table pwz(
    id int generated by default as identity primary key,
    google_id varchar not null unique,
    folder_google_id varchar not null unique,
    address varchar(255) not null unique,
    pay_rate double precision not null check (pay_rate > 0),
    root_folder_id int references root_folder(id)
);

create table month_sheet(
    id int generated by default as identity primary key,
    google_id varchar not null unique,
    pwz_id int references pwz(id),
    month_num int not null check (month_num >= 1 and month_num <= 12),
    year_num int not null check (year_num >= 2000 and year_num <= extract(year from current_date) + 1),
    pay_rate double precision check (pay_rate > 0)
);

create table sheet_info(
    id int generated by default as identity primary key,
    month_sheet_id int references month_sheet(id),
    employee_id int references employee(id),
    hours double precision check (hours > 0),
    salary double precision check (salary > 0)
);

create table user_root_folder(
    user_id int references app_user(id) on delete cascade,
    root_folder_id int references root_folder(id) on delete cascade,
    primary key (user_id, root_folder_id)
);

alter table app_settings add column last_root_folder int references root_folder(id);
alter table app_settings add column last_pwz int references pwz(id);
alter table app_settings add column last_month_sheet int references month_sheet(id);

insert into app_settings(id) values (1);

insert into app_role(id, role_name) values (1, 'ROLE_USER');
insert into app_role(id, role_name) values (2, 'ROLE_ADMIN');
insert into app_role(id, role_name) values (3, 'ROLE_OWNER');
