create table "OWNER"(
    id int generated by default as identity primary key,
    name varchar(100) not null,
    password varchar not null
);

create table employee(
    id int generated by default as identity primary key,
    name varchar(100) not null,
    pay_rate double precision,
    gmail varchar(255) unique,
    phone_number varchar(12) unique
);

create table pwz(
    id int generated by default as identity primary key,
    google_id varchar not null unique,
    address varchar(255) not null unique,
    pay_rate double precision not null check (pay_rate > 0)
);

create table month_sheet(
    id int generated by default as identity primary key,
    google_id varchar not null unique,
    pwz_id int references pwz(id),
    month_num int not null check (month_num >= 1 and month_num <= 12),
    year_num int not null check (year_num >= 2000 and year_num <= extract(year from current_date) + 1),
    pay_rate double precision check (pay_rate > 0)
);

create table sheet_info(
    id int generated by default as identity primary key,
    month_sheet_id int references month_sheet(id),
    employee_id int references employee(id),
    hours double precision check (hours > 0),
    salary double precision check (salary > 0)
);

create table app_settings(
    id int generated by default as identity primary key,
    pay_rate double precision check (pay_rate > 0)
);

create table root_folder(
    id int generated by default as identity primary key,
    google_id varchar not null unique,
    title varchar not null,
    app_settings int references app_settings(id)
);

create table owner_root_folder(
    owner_id int references "OWNER"(id) on delete cascade,
    root_folder_id int references root_folder(id) on delete cascade,
    primary key (owner_id, root_folder_id)
);

alter table app_settings add column last_root_folder int references root_folder(id);
alter table app_settings add column last_pwz int references pwz(id);
alter table app_settings add column last_month_sheet int references month_sheet(id);

insert into app_settings(id) values (1);
